export const questionBank=[
  {id:'ee01',cat:'Energia elétrica',q:'Qual equipamento é destinado a interromper correntes de carga e também correntes de curto-circuito?',a:['Chave seccionadora','Disjuntor','Transformador de potencial','Para-raios'],c:1},
  {id:'ee02',cat:'Energia elétrica',q:'Ao encontrar uma pessoa recebendo choque elétrico, qual é a primeira ação segura?',a:['Puxar a pessoa pelas mãos','Jogar água no equipamento','Aproximar-se para avaliar o pulso','Interromper a fonte de energia com segurança'],c:3},
  {id:'ee03',cat:'Energia elétrica',q:'Qual grandeza elétrica representa a oposição à passagem da corrente?',a:['Potência','Resistência','Frequência','Energia'],c:1},
  {id:'ee04',cat:'Energia elétrica',q:'Em um circuito elétrico, qual é a unidade de medida da corrente?',a:['Volt','Ohm','Ampere','Watt'],c:2},
  {id:'ee05',cat:'Energia elétrica',q:'Qual é a função principal de um transformador de potência?',a:['Alterar níveis de tensão','Medir resistência de isolamento','Interromper curto-circuitos','Armazenar energia elétrica'],c:0},
  {id:'ee06',cat:'Energia elétrica',q:'O que pode acontecer quando a corrente ultrapassa a capacidade de um condutor por muito tempo?',a:['Redução permanente da frequência','Sobreaquecimento do condutor','Aumento do isolamento','Eliminação da queda de tensão'],c:1},
  {id:'ee07',cat:'Energia elétrica',q:'Qual dispositivo ajuda a proteger instalações contra sobretensões transitórias?',a:['Contator','Para-raios','Amperímetro','Seccionadora de aterramento'],c:1},
  {id:'ee08',cat:'Energia elétrica',q:'Em um sistema trifásico equilibrado, as fases estão defasadas entre si em:',a:['60 graus','90 graus','120 graus','180 graus'],c:2},
  {id:'ee09',cat:'Energia elétrica',q:'Qual é a principal função do aterramento de proteção?',a:['Elevar a tensão nominal','Oferecer caminho para correntes de falha','Aumentar o consumo da carga','Substituir a proteção do circuito'],c:1},
  {id:'ee10',cat:'Energia elétrica',q:'Antes de operar um equipamento elétrico com sinais de aquecimento anormal, deve-se:',a:['Aumentar sua carga','Ignorar se ainda estiver funcionando','Avaliar a condição e comunicar a anormalidade','Resfriá-lo diretamente com água'],c:2},

  {id:'ef01',cat:'EPIs e ferramentas elétricas',q:'Antes de utilizar um EPI para trabalho elétrico, o trabalhador deve:',a:['Verificar sua integridade e validade','Compartilhá-lo sem inspeção','Modificá-lo para ficar confortável','Usá-lo somente quando houver supervisão'],c:0},
  {id:'ef02',cat:'EPIs e ferramentas elétricas',q:'Qual é o procedimento mais seguro ao usar um detector de tensão?',a:['Testá-lo apenas depois da medição','Confiar somente no indicador visual','Testá-lo antes e depois em uma fonte conhecida','Encostá-lo diretamente com as mãos'],c:2},
  {id:'ef03',cat:'EPIs e ferramentas elétricas',q:'Uma ferramenta isolada apresenta corte e desgaste na camada de proteção. O que fazer?',a:['Cobrir o dano com fita isolante','Usar somente em baixa tensão','Retirar de uso e providenciar avaliação','Continuar usando com luva comum'],c:2},
  {id:'ef04',cat:'EPIs e ferramentas elétricas',q:'Qual EPI protege principalmente os olhos contra partículas e projeções?',a:['Protetor auricular','Óculos de segurança','Calçado de segurança','Respirador semifacial'],c:1},
  {id:'ef05',cat:'EPIs e ferramentas elétricas',q:'Por que a classe da luva isolante deve ser compatível com a instalação?',a:['Para combinar com a cor do uniforme','Para suportar o nível de tensão previsto','Para dispensar a sobreluva','Para aumentar a sensibilidade das mãos'],c:1},
  {id:'ef06',cat:'EPIs e ferramentas elétricas',q:'Antes de usar um alicate amperímetro, deve-se confirmar:',a:['A categoria de medição e o limite do instrumento','Somente a cor do equipamento','A marca da ferramenta','A temperatura da sala'],c:0},
  {id:'ef07',cat:'EPIs e ferramentas elétricas',q:'Qual prática é correta para conservar luvas isolantes?',a:['Guardá-las dobradas sob ferramentas','Expor ao sol para secar rapidamente','Armazená-las protegidas de perfurações e contaminantes','Aplicar solvente para limpeza'],c:2},
  {id:'ef08',cat:'EPIs e ferramentas elétricas',q:'Uma ferramenta elétrica portátil está com o cabo de alimentação danificado. A ação correta é:',a:['Improvisar uma emenda e continuar','Retirar a ferramenta de uso','Segurar o cabo durante a operação','Usar apenas por poucos minutos'],c:1},
  {id:'ef09',cat:'EPIs e ferramentas elétricas',q:'A vestimenta de proteção contra arco elétrico deve ser selecionada considerando:',a:['Somente o tamanho do trabalhador','O risco e a energia incidente da atividade','A cor usada pela equipe','A duração total do turno'],c:1},
  {id:'ef10',cat:'EPIs e ferramentas elétricas',q:'Ao utilizar uma ferramenta isolada, a proteção do cabo permite:',a:['Trabalhar sem procedimento','Reduzir o risco de contato, dentro de sua especificação','Dispensar a desenergização','Tocar deliberadamente partes energizadas'],c:1},

  {id:'ce01',cat:'Controle de energia',q:'Qual é a principal finalidade do bloqueio e da etiquetagem?',a:['Identificar quem terminou primeiro','Impedir energização ou liberação inesperada','Reduzir o tempo da manutenção','Facilitar o acionamento remoto'],c:1},
  {id:'ce02',cat:'Controle de energia',q:'Após desligar e bloquear uma fonte elétrica, qual etapa confirma a condição segura para o trabalho?',a:['Verificar a ausência de tensão','Retirar imediatamente a sinalização','Fechar as portas da subestação','Encerrar a ordem de serviço'],c:0},
  {id:'ce03',cat:'Controle de energia',q:'Quem deve retirar um cadeado pessoal de bloqueio ao final do trabalho?',a:['Qualquer pessoa da equipe','Preferencialmente quem aplicou o bloqueio, conforme o procedimento','O primeiro trabalhador que chegar','Somente um visitante autorizado'],c:1},
  {id:'ce04',cat:'Controle de energia',q:'Antes de iniciar o bloqueio, é essencial identificar:',a:['Apenas a alimentação principal','Todas as fontes de energia envolvidas','Somente a energia elétrica','A quantidade de ferramentas'],c:1},
  {id:'ce05',cat:'Controle de energia',q:'Energia residual é aquela que:',a:['Permanece armazenada após o desligamento','Existe somente em circuitos novos','É produzida pelo aterramento','Não oferece qualquer risco'],c:0},
  {id:'ce06',cat:'Controle de energia',q:'Qual ação ajuda a controlar energia armazenada em capacitores?',a:['Aumentar a tensão antes do serviço','Aguardar e realizar descarga conforme o procedimento','Retirar apenas a etiqueta','Fechar novamente o disjuntor'],c:1},
  {id:'ce07',cat:'Controle de energia',q:'Em um bloqueio coletivo, cada trabalhador exposto deve:',a:['Confiar somente no cadeado do supervisor','Participar conforme o sistema de bloqueio definido','Retirar cadeados de outros trabalhadores','Ignorar a caixa de bloqueio'],c:1},
  {id:'ce08',cat:'Controle de energia',q:'A etiqueta de bloqueio deve permitir identificar:',a:['O responsável e a condição do bloqueio','O preço do equipamento','Somente o fabricante do cadeado','A próxima data de manutenção'],c:0},
  {id:'ce09',cat:'Controle de energia',q:'Após concluir o serviço e antes da reenergização, deve-se:',a:['Verificar a retirada de pessoas, ferramentas e bloqueios conforme o procedimento','Energizar sem comunicação','Deixar aterramentos temporários instalados','Ignorar as proteções do equipamento'],c:0},
  {id:'ce10',cat:'Controle de energia',q:'Quando existem fontes elétrica, pneumática e hidráulica em uma máquina, o bloqueio deve abranger:',a:['Somente a fonte elétrica','Somente a fonte de maior pressão','Todas as fontes capazes de causar movimento ou dano','A fonte mais próxima do operador'],c:2},

  {id:'sm01',cat:'Simulador de manobras',q:'Antes de colocar um gerador em paralelo com o sistema, o simulador deve exigir a verificação de:',a:['Apenas a corrente do gerador','Tensão, frequência, sequência e ângulo de fase compatíveis','Somente a posição do disjuntor','Apenas a potência ativa da carga'],c:1},
  {id:'sm02',cat:'Simulador de manobras',q:'Qual é o principal benefício de treinar uma sequência de manobras no SimuSystem?',a:['Substituir todas as autorizações operacionais','Eliminar a necessidade de procedimentos','Praticar decisões e identificar erros sem expor o sistema real','Permitir qualquer manobra sem análise de risco'],c:2},
  {id:'sm03',cat:'Simulador de manobras',q:'Durante uma simulação, um alarme de subtensão 27 indica:',a:['Tensão abaixo do limite ajustado','Sobrecorrente de fase instantânea','Frequência acima do limite','Temperatura elevada no transformador'],c:0},
  {id:'sm04',cat:'Simulador de manobras',q:'No simulador, tentar fechar um disjuntor sem as permissivas atendidas deve resultar em:',a:['Fechamento automático','Sinalização do erro e bloqueio da ação insegura','Desligamento do computador','Aumento da tensão da barra'],c:1},
  {id:'sm05',cat:'Simulador de manobras',q:'Qual situação deve ser verificada antes de fechar uma interligação entre duas barras energizadas?',a:['Compatibilidade elétrica e condições de sincronismo','Somente o nome das barras','A quantidade de operadores na sala','A temperatura externa'],c:0},
  {id:'sm06',cat:'Simulador de manobras',q:'Em um treinamento de recomposição após blackout, qual é a prioridade inicial?',a:['Fechar todos os disjuntores ao mesmo tempo','Confirmar o estado do sistema e seguir a sequência de recomposição','Elevar todas as cargas ao máximo','Ignorar alarmes antigos e atuais'],c:1},
  {id:'sm07',cat:'Simulador de manobras',q:'O contador de erros do simulador serve principalmente para:',a:['Punir o participante','Registrar oportunidades de aprendizagem durante o treinamento','Alterar os ajustes dos relés reais','Aumentar automaticamente a carga'],c:1},
  {id:'sm08',cat:'Simulador de manobras',q:'Ao simular a transferência de carga entre barras A e B, deve-se observar:',a:['Capacidade das fontes, posição dos equipamentos e sequência prevista','Somente a cor do diagrama','A velocidade da internet','A quantidade de telas abertas'],c:0},
  {id:'sm09',cat:'Simulador de manobras',q:'Um alarme 50N apresentado no simulador está associado a:',a:['Sobrecorrente instantânea de neutro/terra','Subtensão temporizada','Potência reversa','Falha de sincronismo'],c:0},
  {id:'sm10',cat:'Simulador de manobras',q:'Por que o simulador não substitui o procedimento operacional oficial?',a:['Porque serve para treinamento e deve reproduzir as regras vigentes','Porque não permite aprender sequências','Porque elimina todos os riscos reais','Porque dispensa atualização quando o sistema muda'],c:0}
,
  {id:'ee11',cat:'Energia elétrica',q:'Qual é a diferença entre potência elétrica e energia elétrica?',a:['Potência é a taxa de consumo ou geração; energia é essa potência acumulada no tempo','São exatamente a mesma grandeza','Potência é medida em ampere e energia em volt','Energia existe apenas em corrente contínua'],c:0},
  {id:'ee12',cat:'Energia elétrica',q:'Quando um disjuntor atua por uma condição de falha, antes de religá-lo deve-se:',a:['Religar repetidamente até permanecer fechado','Identificar e avaliar a causa da atuação','Substituí-lo por outro de corrente maior','Bloquear a atuação da proteção'],c:1},
  {id:'ee13',cat:'Energia elétrica',q:'Qual é a função geral de um relé de proteção?',a:['Detectar condições anormais e comandar ações de proteção','Aumentar a potência da carga','Substituir o aterramento da instalação','Armazenar energia para o circuito'],c:0},
  {id:'ee14',cat:'Energia elétrica',q:'A função de proteção ANSI 50 está normalmente associada a:',a:['Sobrecorrente instantânea','Subtensão temporizada','Potência reversa','Sobrefrequência'],c:0},
  {id:'ee15',cat:'Energia elétrica',q:'A função de proteção ANSI 51 está normalmente associada a:',a:['Sobrecorrente temporizada','Sobretensão instantânea','Falha de sincronismo','Temperatura de mancais'],c:0},
  {id:'ee16',cat:'Energia elétrica',q:'A indicação 51N em um relé geralmente representa:',a:['Sobrecorrente temporizada de neutro ou terra','Sobretensão entre fases','Subfrequência instantânea','Potência ativa elevada'],c:0},
  {id:'ee17',cat:'Energia elétrica',q:'A função ANSI 27 é utilizada para detectar:',a:['Subtensão','Sobrecorrente','Sobrefrequência','Potência reversa'],c:0},
  {id:'ee18',cat:'Energia elétrica',q:'Em uma subestação, qual é a função de uma barra elétrica?',a:['Interligar circuitos para distribuir energia','Medir exclusivamente a frequência','Armazenar energia mecânica','Substituir os relés de proteção'],c:0},
  {id:'ee19',cat:'Energia elétrica',q:'Por que o secundário de um transformador de corrente não deve ser aberto com o primário energizado?',a:['Pode surgir tensão perigosa no secundário','A frequência da rede será reduzida','O disjuntor perderá sua capacidade de interrupção','A barra ficará automaticamente aterrada'],c:0},
  {id:'ee20',cat:'Energia elétrica',q:'Um banco de capacitores é normalmente utilizado para:',a:['Compensar potência reativa e melhorar o fator de potência','Interromper correntes de curto-circuito','Converter corrente alternada em contínua','Substituir transformadores de potência'],c:0},
  {id:'ee21',cat:'Energia elétrica',q:'Em um sistema elétrico interligado, a frequência está relacionada principalmente ao equilíbrio entre:',a:['Geração e carga','Tensão e resistência de isolamento','Temperatura e umidade','Comprimento e cor dos cabos'],c:0},
  {id:'ee22',cat:'Energia elétrica',q:'A perda de uma fase em um motor trifásico pode provocar:',a:['Sobrecorrente e aquecimento','Aumento seguro de potência','Eliminação das vibrações','Melhoria automática do rendimento'],c:0},
  {id:'ee23',cat:'Energia elétrica',q:'O que significa seletividade em um sistema de proteção?',a:['Isolar preferencialmente a parte mais próxima da falha','Desligar toda a instalação em qualquer evento','Usar apenas um relé para toda a rede','Impedir a atuação dos disjuntores de baixa tensão'],c:0},
  {id:'ee24',cat:'Energia elétrica',q:'Como um voltímetro deve ser conectado para medir a tensão entre dois pontos?',a:['Em paralelo entre os pontos','Em série com toda a carga','Somente ao condutor de proteção','Curto-circuitando os pontos'],c:0},
  {id:'ee25',cat:'Energia elétrica',q:'Ao medir corrente com um alicate amperímetro, normalmente deve-se envolver:',a:['Apenas um condutor do circuito','Todos os condutores juntos','O cabo de aterramento e o neutro juntos','A carcaça metálica do equipamento'],c:0},

  {id:'ef11',cat:'EPIs e ferramentas elétricas',q:'A seleção de uma proteção facial para risco de arco elétrico deve considerar:',a:['A análise de risco e a proteção compatível com a energia incidente','Somente a transparência do visor','A cor do capacete','A preferência estética do usuário'],c:0},
  {id:'ef12',cat:'EPIs e ferramentas elétricas',q:'Um capacete de segurança com trincas ou deformações deve ser:',a:['Retirado de uso e substituído','Reparado com cola e utilizado','Usado apenas em serviços rápidos','Coberto com adesivo para ocultar o dano'],c:0},
  {id:'ef13',cat:'EPIs e ferramentas elétricas',q:'Um calçado destinado ao trabalho elétrico está molhado e contaminado. O trabalhador deve:',a:['Retirá-lo de uso até limpeza, secagem e avaliação adequadas','Usá-lo normalmente porque o solado é grosso','Cobri-lo com um saco plástico','Secá-lo durante o trabalho em parte energizada'],c:0},
  {id:'ef14',cat:'EPIs e ferramentas elétricas',q:'A categoria CAT de um instrumento de medição indica:',a:['A aptidão para suportar transientes no ambiente de medição especificado','A precisão da cor do visor','O tamanho físico do instrumento','O período entre trocas de bateria'],c:0},
  {id:'ef15',cat:'EPIs e ferramentas elétricas',q:'Pontas de prova com isolamento rachado devem ser:',a:['Substituídas antes da medição','Enroladas com papel','Utilizadas apenas com uma mão','Molhadas para melhorar o contato'],c:0},
  {id:'ef16',cat:'EPIs e ferramentas elétricas',q:'Além da calibração aplicável, antes de medir tensão é importante:',a:['Fazer inspeção e teste funcional do instrumento','Selecionar sempre a menor escala possível','Desativar os dispositivos de proteção','Segurar as partes metálicas das pontas'],c:0},
  {id:'ef17',cat:'EPIs e ferramentas elétricas',q:'Qual é a finalidade de um tapete isolante adequado ao serviço?',a:['Reduzir o risco de contato do trabalhador com o potencial de terra','Substituir todas as demais medidas de controle','Eliminar a necessidade de inspeção','Aumentar a corrente disponível'],c:0},
  {id:'ef18',cat:'EPIs e ferramentas elétricas',q:'Antes do uso, a luva isolante deve passar por:',a:['Inspeção visual e teste de ar conforme orientação aplicável','Lavagem com solvente','Perfuração para melhorar a ventilação','Dobramento repetido junto ao punho'],c:0},
  {id:'ef19',cat:'EPIs e ferramentas elétricas',q:'Qual é a função da sobreluva de couro usada sobre a luva isolante?',a:['Proteger a luva de borracha contra danos mecânicos','Aumentar sua classe de tensão','Substituir os ensaios periódicos','Permitir o uso de uma luva perfurada'],c:0},
  {id:'ef20',cat:'EPIs e ferramentas elétricas',q:'Quando a atividade apresenta nível de ruído acima do permitido, deve-se:',a:['Adotar controles e usar proteção auditiva adequada quando indicada','Usar somente óculos de segurança','Retirar o capacete para ouvir melhor','Reduzir apenas a iluminação do local'],c:0},
  {id:'ef21',cat:'EPIs e ferramentas elétricas',q:'A roupa para proteção contra arco elétrico:',a:['Não substitui as medidas de proteção contra choque elétrico','Permite tocar partes energizadas','Dispensa bloqueio e sinalização','Elimina todos os riscos térmicos'],c:0},
  {id:'ef22',cat:'EPIs e ferramentas elétricas',q:'Uma ferramenta isolada deve possuir especificação compatível com:',a:['A tensão e a atividade previstas','Somente o peso do equipamento','A cor da instalação','O horário de execução'],c:0},
  {id:'ef23',cat:'EPIs e ferramentas elétricas',q:'Para trabalhos próximos a instalações elétricas, a escada deve ser escolhida considerando:',a:['Material não condutivo apropriado e condições da tarefa','Somente o maior comprimento disponível','Estrutura metálica sem inspeção','A possibilidade de apoiá-la em condutores'],c:0},
  {id:'ef24',cat:'EPIs e ferramentas elétricas',q:'Ferramentas e EPIs destinados a serviços elétricos devem ser mantidos:',a:['Limpos, secos e armazenados conforme orientação do fabricante','Misturados com produtos químicos','Expostos ao sol continuamente','Sob objetos pesados'],c:0},
  {id:'ef25',cat:'EPIs e ferramentas elétricas',q:'Antes de uma atividade elétrica, adornos metálicos como anéis e correntes devem ser:',a:['Retirados conforme os requisitos de segurança','Cobertos somente com fita comum','Mantidos por baixo da luva','Usados para auxiliar no aterramento'],c:0},

  {id:'ce11',cat:'Controle de energia',q:'Após aplicar o bloqueio, tentar acionar o comando de partida serve para:',a:['Verificar se o isolamento impede o funcionamento, conforme procedimento','Reenergizar o equipamento','Substituir a verificação de ausência de tensão','Retirar a energia residual automaticamente'],c:0},
  {id:'ce12',cat:'Controle de energia',q:'Por que uma etiqueta sozinha normalmente não equivale a um bloqueio físico?',a:['Porque ela informa, mas não impede mecanicamente a operação','Porque não pode identificar o responsável','Porque aumenta a energia armazenada','Porque sempre desliga o circuito'],c:0},
  {id:'ce13',cat:'Controle de energia',q:'Em um sistema com caixa de bloqueio coletivo, as chaves dos bloqueios das fontes ficam:',a:['Controladas na caixa enquanto cada participante mantém seu bloqueio pessoal','Com qualquer pessoa que passe pelo local','Inseridas nos equipamentos energizados','Descartadas após o início do serviço'],c:0},
  {id:'ce14',cat:'Controle de energia',q:'Na troca de turno, a continuidade segura do bloqueio exige:',a:['Transferência formal de responsabilidade sem deixar a instalação desprotegida','Retirada de todos os cadeados antes da chegada da nova equipe','Entrega informal das chaves a qualquer colega','Reenergização para confirmar o funcionamento'],c:0},
  {id:'ce15',cat:'Controle de energia',q:'Além da eletricidade, qual exemplo representa energia perigosa armazenada?',a:['Parte elevada que pode cair pela gravidade','Etiqueta fixada no painel','Lâmpada indicadora desligada','Documento arquivado'],c:0},
  {id:'ce16',cat:'Controle de energia',q:'Para controlar energia pneumática residual, pode ser necessário:',a:['Bloquear a alimentação e aliviar a pressão conforme procedimento','Aumentar a pressão antes do serviço','Fechar apenas o comando elétrico','Retirar os dispositivos de alívio'],c:0},
  {id:'ce17',cat:'Controle de energia',q:'Em um sistema hidráulico, uma carga suspensa deve ser:',a:['Baixada ou bloqueada mecanicamente de modo seguro','Mantida apenas pela pressão hidráulica','Movimentada durante a manutenção','Sustentada pelo botão de parada'],c:0},
  {id:'ce18',cat:'Controle de energia',q:'O estado de energia zero significa que:',a:['As fontes foram isoladas e as energias residuais controladas e verificadas','Somente o painel foi desligado','A iluminação do local está apagada','O equipamento está no modo automático'],c:0},
  {id:'ce19',cat:'Controle de energia',q:'Antes e após um procedimento de bloqueio, os trabalhadores afetados devem:',a:['Ser comunicados conforme o procedimento','Retirar os cadeados dos executantes','Alterar os ajustes das proteções','Ignorar a condição operacional'],c:0},
  {id:'ce20',cat:'Controle de energia',q:'Se o responsável por um cadeado pessoal não estiver presente, sua retirada deve ocorrer:',a:['Somente por procedimento formal, autorizado e verificado','Por qualquer operador disponível','Com corte imediato sem comunicação','Após energizar o equipamento'],c:0},
  {id:'ce21',cat:'Controle de energia',q:'Um equipamento possui alimentação principal e uma fonte auxiliar. Para trabalho seguro deve-se:',a:['Identificar e isolar ambas quando apresentarem risco','Bloquear somente a fonte principal','Desligar apenas a iluminação do painel','Confiar no diagrama sem verificar o campo'],c:0},
  {id:'ce22',cat:'Controle de energia',q:'Acionar o botão de parada de uma máquina é suficiente para isolar energia?',a:['Não, o circuito de comando não substitui o isolamento das fontes','Sim, em qualquer situação','Sim, desde que a lâmpada apague','Sim, quando houver etiqueta no botão'],c:0},
  {id:'ce23',cat:'Controle de energia',q:'Ao preparar o bloqueio, diagramas e listas de fontes devem ser:',a:['Conferidos com a instalação e as condições reais de campo','Aceitos sem qualquer verificação','Substituídos por memória dos operadores','Ignorados quando a tarefa for curta'],c:0},
  {id:'ce24',cat:'Controle de energia',q:'Se for indispensável energizar temporariamente para um teste durante a manutenção, deve-se:',a:['Seguir sequência controlada de retirada, teste, nova desenergização e bloqueio','Retirar todos os bloqueios definitivamente','Manter pessoas em partes móveis','Cancelar a análise de risco'],c:0},
  {id:'ce25',cat:'Controle de energia',q:'O encerramento de um bloqueio deve registrar e confirmar:',a:['Condição do equipamento, retirada correta dos dispositivos e comunicação','Somente o horário de almoço','A cor dos cadeados utilizados','A quantidade de mensagens enviadas'],c:0},

  {id:'sm11',cat:'Simulador de manobras',q:'A cor de um equipamento no diagrama do simulador é suficiente para confirmar sua posição real?',a:['Não, deve-se considerar as indicações e confirmações previstas','Sim, a cor elimina qualquer outra verificação','Sim, mesmo quando houver alarme de discordância','Não, porque cores nunca têm função em diagramas'],c:0},
  {id:'sm12',cat:'Simulador de manobras',q:'No simulador, o comando indica disjuntor fechado, mas o retorno de posição permanece aberto. Isso sugere:',a:['Discordância que deve ser investigada antes de prosseguir','Operação normal sem importância','Sincronismo automaticamente aprovado','Ausência garantida de tensão'],c:0},
  {id:'sm13',cat:'Simulador de manobras',q:'Qual é a finalidade de um intertravamento representado no simulador?',a:['Impedir uma sequência incompatível ou insegura','Aumentar a corrente de curto-circuito','Ocultar alarmes do operador','Substituir o treinamento'],c:0},
  {id:'sm14',cat:'Simulador de manobras',q:'Antes de executar uma manobra, a visualização da topologia ajuda a:',a:['Identificar fontes, conexões e possíveis efeitos da operação','Escolher a cor dos equipamentos','Eliminar todas as permissivas','Dispensar a comunicação com a equipe'],c:0},
  {id:'sm15',cat:'Simulador de manobras',q:'Para interromper corrente de carga em uma sequência de manobra, deve-se utilizar primeiro:',a:['O equipamento com capacidade de interrupção, como o disjuntor','A seccionadora sem capacidade para carga','A chave de aterramento','O transformador de potencial'],c:0},
  {id:'sm16',cat:'Simulador de manobras',q:'Ao simular o paralelismo de transformadores, deve-se verificar, entre outros fatores:',a:['Compatibilidade de tensões, relações, polaridade e condições de operação','Somente a cor das placas','A distância até a sala de controle','A quantidade de alarmes antigos'],c:0},
  {id:'sm17',cat:'Simulador de manobras',q:'Antes de fechar um anel elétrico no simulador, é importante avaliar:',a:['Condições elétricas e o fluxo de potência resultante','Somente o tempo restante do exercício','A marca dos disjuntores','O número de participantes'],c:0},
  {id:'sm18',cat:'Simulador de manobras',q:'Durante a transferência para uma fonte de emergência, a sequência deve priorizar:',a:['Cargas essenciais e limites da fonte conforme o procedimento','Todas as cargas simultaneamente','Cargas não essenciais de maior consumo','O fechamento sem verificar tensão'],c:0},
  {id:'sm19',cat:'Simulador de manobras',q:'Na recomposição de cargas após uma interrupção, por que a entrada costuma ser gradual?',a:['Para observar limites e evitar sobrecarga ou nova instabilidade','Para reduzir a tensão nominal permanentemente','Para desativar os relés','Para impedir qualquer registro de evento'],c:0},
  {id:'sm20',cat:'Simulador de manobras',q:'Um desligamento geral inesperado no exercício deve levar o participante primeiro a:',a:['Avaliar alarmes, estados e causa provável antes da recomposição','Fechar imediatamente todos os equipamentos','Ignorar a sequência operacional','Apagar o histórico de eventos'],c:0},
  {id:'sm21',cat:'Simulador de manobras',q:'Qual é a utilidade do registro cronológico de eventos do simulador?',a:['Analisar a sequência de comandos, alarmes e atuações','Aumentar a potência disponível','Substituir as proteções reais','Ocultar erros do treinamento'],c:0},
  {id:'sm22',cat:'Simulador de manobras',q:'Cenários aleatórios de falha em um simulador ajudam a:',a:['Treinar diagnóstico e resposta sem depender de uma sequência decorada','Eliminar a necessidade de conhecimento técnico','Garantir que toda resposta esteja correta','Evitar a avaliação do participante'],c:0},
  {id:'sm23',cat:'Simulador de manobras',q:'Após uma manobra simulada, os valores de tensão e corrente devem ser:',a:['Comparados com o comportamento esperado e os limites operacionais','Ignorados quando não houver alarme sonoro','Substituídos por valores escolhidos pelo usuário','Avaliados somente ao final do ano'],c:0},
  {id:'sm24',cat:'Simulador de manobras',q:'Quando a configuração da instalação real é alterada, o modelo do simulador deve ser:',a:['Revisado e atualizado para representar a nova condição','Mantido inalterado para preservar exercícios antigos','Desativado definitivamente','Usado sem comunicar os participantes'],c:0},
  {id:'sm25',cat:'Simulador de manobras',q:'Após concluir um cenário, a análise dos acertos e erros serve para:',a:['Consolidar aprendizados e melhorar decisões futuras','Modificar equipamentos reais automaticamente','Eliminar os procedimentos oficiais','Reduzir a quantidade de proteções'],c:0}
];

function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}

export function buildQuiz(){
  let recent=[];
  try{recent=JSON.parse(localStorage.getItem('desafioRecentQuestions')||'[]')}catch(e){}
  const available=questionBank.filter(q=>!recent.includes(q.id));
  const source=available.length>=20?available:questionBank;
  const categories=[...new Set(questionBank.map(q=>q.cat))];
  const selected=[];
  categories.forEach(cat=>selected.push(...shuffle(source.filter(q=>q.cat===cat)).slice(0,2)));
  const remaining=source.filter(q=>!selected.some(s=>s.id===q.id));
  selected.push(...shuffle(remaining).slice(0,10-selected.length));
  const quiz=shuffle(selected).map(q=>{
    const options=shuffle(q.a.map((text,index)=>({text,correct:index===q.c})));
    return{...q,a:options.map(o=>o.text),c:options.findIndex(o=>o.correct)};
  });
  try{localStorage.setItem('desafioRecentQuestions',JSON.stringify(quiz.map(q=>q.id)))}catch(e){}
  return quiz;
}
